---
title: "Airbnb: Causal Inference"
subtitle: "Inferring Causal Effects of Marketing Ads on User Bookings"
author: "Andrew Pagtakhan"
date: "12/4/2020"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
    number_section: true
---

R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32

```{r setup, include=FALSE}
# installs packages if needed
if(!requireNamespace("arm"))
  install.packages("arm")
if(!requireNamespace("here"))
  install.packages("here")
if(!requireNamespace("tidyverse"))
  install.packages("tidyverse")
if(!requireNamespace("BART"))
  install.packages("BART")

# increase memory limit for matching functions
# make sure this limit is compatible with the system used to run this code
memory.limit(3.2e10)
```

```{r, warning = FALSE, message = FALSE}
library(arm)
library(BART) # Bayesian Additive Regression Trees
library(here)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, tidy.opts=list(width.cutoff=60), tidy=TRUE)
seed <- 14
set.seed(seed)
```


# Load Data

```{r, message = FALSE}
# load bookings data
book <- read_csv(here("data", "bookings_sample.csv"))
```


# Exploratory Data Analysis

## User demographics and overlap
See Tableau dashboard link below:

**https://public.tableau.com/profile/andrew.pagtakhan#!/vizhome/NYU_Causal_Airbnb/destination**

## Balance

# Modeling

## Logistic Regression

```{r}
# see preliminary effects using logistic model
summary(lr <- glm(is_booked ~ age + gender + treat + 
                              is_mobile + browser_group + is_eng, 
                  data = book, 
                  family = binomial(link = "logit")))

# get propensity scores
book$ps_lr <- predict(lr, type = "response")
tapply(book$ps_lr, book$is_booked, mean)
```


```{r}
# define color palette for graphs
col.pal <- c("#999999", "#E69F00", "#56B4E9", "#777777")

# plot propensity scores
book %>% 
  ggplot(aes(x = ps_lr, fill = as.factor(is_booked))) +
  geom_histogram(alpha = 0.5) + 
  labs(title = "Propensity Score Distribution: Logistic Regression") + 
  theme(legend.position = "bottom") +
  scale_fill_manual(values = col.pal)
```


### BART

```{r}
# convert variables for BART model
book$gender <- as.factor(book$gender)
book$first_device_type <- as.factor(book$first_device_type)
book$browser_group <- as.factor(book$browser_group)
```

```{r, cache = TRUE}
# run BART on sample data due to computational time
bart_sample <- 1000
book_sample <- sample_n(book, bart_sample)
# get covariates for model
xtrain_bart <- as.data.frame(book_sample %>% 
                               select(age, gender, treat, is_mobile, 
                                      browser_group, is_eng))
# run predictions on all data
xtest_bart <- as.data.frame(book %>% 
                                select(age, gender, treat, is_mobile, 
                                      browser_group, is_eng))

# fit and predict
bart <- gbart(x.train = xtrain_bart,  
              y.train = book_sample$is_booked,
              x.test = xtest_bart,
              type = "lbart",
              seed = seed,
              mc.cores = 2)

# add prop scores on full dataset
book$ps_bart <- bart$prob.test.mean
```


```{r, message=FALSE}
# define color palette for graphs
col.pal <- c("#999999", "#E69F00", "#56B4E9", "#777777")

# average propensity scores for plot
bart_prop <- book %>% 
             group_by(is_booked) %>% 
             summarise(avg = mean(ps_bart))

# plot propensity scores
book %>% 
  ggplot(aes(x = ps_bart, fill = as.factor(is_booked))) +
  geom_histogram(alpha = 0.5) + 
  geom_vline(data = bart_prop, aes(xintercept = avg, 
                                   colour = as.factor(is_booked))) +
  labs(title = "Propensity Score Distribution: BART",
       subtitle = "Vertical Lines: Average propensity scores") + 
  theme(legend.position = "bottom") +
  scale_fill_manual(values = col.pal) + 
  scale_color_manual(values = col.pal)
``` 



### Matching
```{r, cache = TRUE}
# 1-1 neighbor matching
matched_bart <- matching(z = book$treat, 
                         score = book$ps_bart, 
                         replace = TRUE)$cnts
# add matched counts to df
book$nn_cnts <- matched_bart
```

```{r}
# inspect top 10 records used for matching
book %>% 
  arrange(desc(nn_cnts)) %>% 
  select(age, gender, is_mobile, browser_group, is_eng, nn_cnts) %>% 
  top_n(10, nn_cnts)
```


### Balance
```{r}
#bal_lr <- balance(book_sample, 
#                  treat = book_sample$treat, 
#                  matched = matched_lr, 
#                  estimand = "ATT")
```



## CART
Classification and Regression Trees


# Causal Effect Estimation