---
title: "Propensity Score Matching"
author: "Diana Liang"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd('E:/NYU/2020FALL/Causal/project')

library(dplyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(rpart)
library(ranger)
library(MatchIt)
library(optmatch)
library(Hmisc)
library(survey)
library(arm)
library(gbm)
library(correlationfunnel)
library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")

theme_set(theme_bw())

# read in data
dat <- read_csv('bookings_sample.csv')

# convert categorical variables
dat <- dat %>% mutate_at(vars(c("gender","browser_group")),as.factor)
```


# Logistic Regression
```{r}
fit.lr <- glm(treat~is_eng+is_mobile+age+days_diff+gender+browser_group,family=binomial,data=dat)

dat$pscores.lr <- predict(fit.lr,type='response')

ggplot(dat) +
  geom_histogram(aes(pscores.lr,col=factor(treat)),alpha=0) +
  scale_color_manual(
    name='Group',
    labels=c('control','treatment'),
    values=c('blue','red')
  )

## one-to-one nearest neighbor w/ replacement
matches.lr <- matching(z=dat$treat,score=dat$pscores.lr,replace=T)
weight.lr <- ifelse(dat$treat==0,matches.lr$cnts,1)

## IPTW
IPTW.lr <- dat %>% 
  transmute(IPTW=ifelse(treat==1,1,pscores.lr/(1-pscores.lr))) %>% 
  unlist() %>% 
  unname()
```


# Probit Regression
```{r}
fit.prob <- glm(treat~is_eng+is_mobile+age+days_diff+gender+browser_group,family=binomial(link='probit'),data=dat)

dat$pscores.prob <- predict(fit.prob,type='response')

ggplot(dat) +
  geom_histogram(aes(pscores.prob,col=factor(treat)),alpha=0) +
  scale_color_manual(
    name='Group',
    labels=c('control','treatment'),
    values=c('blue','red')
  )

## one-to-one nearest neighbor w/ replacement
matches.prob <- matching(z=dat$treat,score=dat$pscores.prob,replace=T)
weight.prob <- ifelse(dat$treat==0,matches.prob$cnts,1)

## IPTW
IPTW.prob <- dat %>% 
  transmute(IPTW=ifelse(treat==1,1,pscores.prob/(1-pscores.prob))) %>% 
  unlist() %>% 
  unname()
```

# CART
```{r}
fit.cart <- rpart(treat~is_eng+is_mobile+age+days_diff+gender+browser_group,data=dat,method='class') # fit a CART model

dat$pscores.cart <- predict(fit.cart,type='prob')[,2] # take probability of assigned=1 as propensity scores

ggplot(dat) +
  geom_histogram(aes(pscores.cart,col=factor(treat)),alpha=0) +
  scale_color_manual(
    name='Group',
    labels=c('control','treatment'),
    values=c('blue','red')
  )

## one-to-one nearest neighbor w/ replacement
matches.cart <- matching(z=dat$treat,score=dat$pscores.cart,replace=T)
weight.cart <- ifelse(dat$treat==0,matches.cart$cnts,1)

## IPTW
IPTW.cart <- dat %>% 
  transmute(IPTW=ifelse(treat==1,1,pscores.cart/(1-pscores.cart))) %>% 
  unlist() %>% 
  unname()
```


# Random Forest
```{r}
fit.rf <- ranger(treat~is_eng+is_mobile+age+days_diff+gender+browser_group,data=dat)

dat$pscores.rf <- predict(fit.rf,data=dat)$predictions

ggplot(dat) +
  geom_histogram(aes(pscores.rf,col=factor(treat)),alpha=0) +
  scale_color_manual(
    name='Group',
    labels=c('control','treatment'),
    values=c('blue','red')
  )

## one-to-one nearest neighbor w/ replacement
matches.rf <- matching(z=dat$treat,score=dat$pscores.rf,replace=T)
weight.rf <- ifelse(dat$treat==0,matches.rf$cnts,1)

## IPTW
IPTW.rf <- dat %>% 
  transmute(IPTW=ifelse(treat==1,1,pscores.rf/(1-pscores.rf))) %>% 
  unlist() %>% 
  unname()
```

# GBM
```{r}
fit.gbm <- gbm(treat~is_eng+is_mobile+age+days_diff+gender+browser_group,data=dat)

dat$pscores.gbm <- predict(fit.gbm)

ggplot(dat) +
  geom_histogram(aes(pscores.gbm,col=factor(treat)),alpha=0) +
  scale_color_manual(
    name='Group',
    labels=c('control','treatment'),
    values=c('blue','red')
  )

## one-to-one nearest neighbor w/ replacement
matches.gbm <- matching(z=dat$treat,score=dat$pscores.gbm,replace=T)
weight.gbm <- ifelse(dat$treat==0,matches.gbm$cnts,1)

## IPTW
IPTW.gbm <- dat %>% 
  transmute(IPTW=ifelse(treat==1,1,pscores.gbm/(1-pscores.gbm))) %>% 
  unlist() %>% 
  unname()
```

```{r}
# recode categorical
cat <- dat %>% select(gender,browser_group) %>% binarize()
dat <- bind_cols(dat,cat)

# covariate list
cov <- c('is_eng','is_mobile','age','days_diff',names(cat))

# examine balance
check_balance <- function(data,covariates,weights){
  out <- list()
  for(cov in covariates){
    prematch_mean_trt <- sapply(data[data$treat==1,cov],mean)
    prematch_mean_ctr <- sapply(data[data$treat==0,cov],mean)
    matched_mean_trt <- weighted.mean(t(data[data$treat==1,cov]),weights[data$treat==1])
    matched_mean_ctr <- weighted.mean(t(data[data$treat==0,cov]),weights[data$treat==0])
    prematch_mean_diff <- ifelse(n_distinct(data[,cov])==2,prematch_mean_trt-prematch_mean_ctr,(prematch_mean_trt-prematch_mean_ctr)/sapply(data[data$treat==1,cov],sd))
    matched_mean_diff <- ifelse(n_distinct(data[,cov])==2,matched_mean_trt-matched_mean_ctr,(matched_mean_trt-matched_mean_ctr)/sapply(data[data$treat==1,cov],sd))
    prematch_sd_r <- sapply(data[data$treat==0,cov],sd)/sapply(data[data$treat==1,cov],sd)
    matched_sd_r <- sqrt(wtd.var(t(data[data$treat==0,cov]),weights[data$treat==0]))/sqrt(wtd.var(t(data[data$treat==1,cov]),weights[data$treat==1]))
    # format output as one df for each cov
    out[[cov]] <- tibble(cov,prematch_mean_diff,matched_mean_diff,prematch_sd_r,matched_sd_r)
    out[[cov]] <- tibble(cov=rep(cov,4),
                         metrics=rep(c('SMD','VR'),each=2),
                         matched=rep(c('prematch','matched'),2),
                         values=c(prematch_mean_diff,matched_mean_diff,prematch_sd_r,matched_sd_r))
  }
  out_df <- bind_rows(out)
  return(out_df)
}

# check balance for each method
balance_lr.nn <- check_balance(dat,cov,weight.lr) %>% mutate(method='LR 1-1NN')
balance_lr.IPTW <- check_balance(dat,cov,IPTW.lr) %>% mutate(method='LR IPTW')
balance_prob.nn <- check_balance(dat,cov,weight.prob) %>% mutate(method='PR 1-1NN')
balance_prob.IPTW <- check_balance(dat,cov,IPTW.prob) %>% mutate(method='PR IPTW')
balance_cart.nn <- check_balance(dat,cov,weight.cart) %>% mutate(method='CART 1-1NN')
balance_cart.IPTW <- check_balance(dat,cov,IPTW.cart) %>% mutate(method='CART IPTW')
balance_rf.nn <- check_balance(dat,cov,weight.rf) %>% mutate(method='RF 1-1NN')
balance_rf.IPTW <- check_balance(dat,cov,IPTW.rf) %>% mutate(method='RF IPTW')
balance_gbm.nn <- check_balance(dat,cov,weight.gbm) %>% mutate(method='GBM 1-1NN')
balance_gbm.IPTW <- check_balance(dat,cov,IPTW.gbm) %>% mutate(method='GBM IPTW')

# store prematch values
dat_prematch <- balance_lr.nn %>% 
  filter(matched=='prematch') %>% 
  mutate(method='prematch') %>% 
  select(-matched)
# store matched values under different method
dat_balance <- bind_rows(balance_lr.nn,balance_lr.IPTW,balance_prob.nn,balance_prob.IPTW,balance_cart.nn,balance_cart.IPTW,balance_rf.nn,balance_rf.IPTW,balance_gbm.nn,balance_gbm.IPTW) %>%
  filter(matched=='matched') %>%
  select(-matched) %>%
  bind_rows(dat_prematch) %>%
  mutate(method=factor(method,levels=c('prematch','LR 1-1NN','LR IPTW','PR 1-1NN','PR IPTW','CART 1-1NN','CART IPTW','RF 1-1NN','RF IPTW','GBM 1-1NN','GBM IPTW')))

# display balance
## difference in means
dat_balance %>% filter(metrics=='SMD') %>%
  ggplot(aes(method,cov,fill=values)) +
  geom_tile() +
  theme(axis.text.x=element_text(angle=45,vjust=.6)) +
  ylab('covariates') +
  ggtitle('Standardized Difference in Means')
## ratios of standard deviations
dat_balance %>% filter(metrics=='VR') %>%
  ggplot(aes(method,cov,fill=values)) +
  geom_tile() +
  theme(axis.text.x=element_text(angle=45,vjust=.6)) +
  ylab('covariates') +
  ggtitle('Ratios of Standard Deviations')
```

